services:
  ai-zhishengji:
    container_name: ai-zhishengji-web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8080"
    # 移除了 Nginx 相关的卷挂载

  twonav:
    image: tznb/twonav:latest
    container_name: twonav
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - /www/wwwroot/twonav:/www

## 执行命令 
## docker-compose -f docker-compose-nav.yml down
## docker-compose -f docker-compose-nav.yml up --build -d
